server {
    listen       80;
    server_name  etcd.dev.dreamcat.org;

    location / {
        proxy_pass http://$LOCAL_IP:8079/etcdkeeper/;
    }

    location /framework/ {
        proxy_pass http://$LOCAL_IP:8079/framework/;
    }

    location ~ ^/v\d+/ {
        proxy_pass http://$LOCAL_IP:8079$request_uri;
    }
}
