FROM centos

MAINTAINER "tuke tukeof@gmail.com"

COPY CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo

#RUN dnf makecache

## java, zip, unzip, nslookup, dig, wget, vi, curl, ps, top,
#RUN yum install -y java-1.8.0-openjdk-headless fontconfig -y && \
#    yum install -y zip unzip bind-utils wget && \
#    wget dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm && \
#    rpm -ihv epel-release-7-11.noarch.rpm && \
#    rm -f epel-release-7-11.noarch.rpm && \
#    yum install htop -y && \
#    yum clean all -y

