services:
  # depends on mysql8+
  metabase:
    image: metabase/metabase
    container_name: metabase
    networks:
      - dev
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_HOST: postgres
      MB_DB_PASS: postgres
      # MB_DB_FILE: /metabase.db
      JAVA_TIMEZONE: Asia/Shanghai
    volumes:
      - /dev/urandom:/dev/random:ro
      - ./metabase:/metabase.db
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
networks:
  dev:
    external: true
    name: dev
    driver: bridge
