#MB_CONFIG_FILE_PATH

version: 1
config:
  settings:
    config-from-file-sync-databases: false
  users:
    - first_name: Jerry
      last_name: Will
      email: metabase@dreamcat.org
      password: metabase
      is_superuser: true
  databases:
    - name: mysql
      engine: mysql
      host:
      port:
      user: root
      password: "{{ env MYSQL_PASSWORD }}"
      dbname: sampledb
