services:
  flink-jobmanager:
    image: flink
    container_name: flink-jobmanager
    networks:
      - flink
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: flink-jobmanager"

  flink-taskmanager1:
    image: flink
    container_name: flink-taskmanager1
    networks:
      - flink
    command: taskmanager
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: flink-jobmanager"

  flink-taskmanager2:
    image: flink
    container_name: flink-taskmanager2
    networks:
      - flink
    command: taskmanager
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: flink-jobmanager"

networks:
  flink:
    name: flink
    driver: bridge
