services:
  # depends_on mysql:8.3
  dataease:
    image: jerrywill/dataease:v2.8.0
    container_name: dataease
    networks:
      - dev
    ports:
      - "8100:8100"
    volumes:
      - ./conf:/opt/apps/config
      - ./data:/opt/dataease2.0/data
      - ./logs:/opt/dataease2.0/logs

  dataease-etcd:
    image: jerrywill/dataease-etcd:3.5.10
    container_name: dataease-etcd
    hostname: dataease-etcd
    networks:
      - dev
    ports:
      - "2379:2379"
    volumes:
      - ./etcd:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://dataease-etcd:2379"

  dataease-apisix:
    image: jerrywill/dataease-apisix:3.6.0
    container_name: dataease-apisix
    networks:
      - dev
    ports:
      - 9180:9180
      - 9080:9080
    volumes:
      - ./apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/logs:/usr/local/apisix/logs
      - ./apisix/plugins/cas-auth.lua:/usr/local/apisix/apisix/plugins/cas-auth.lua
    environment:
      TZ: "Asia/Shanghai"
    depends_on:
      - dataease-etcd

  dataease-apisix-dashboard:
    image: jerrywill/dataease-apisix-dashboard:3.0.1
    container_name: dataease-apisix-dashboard
    networks:
      - dev
    ports:
      - 9000:9000
    volumes:
      - ./apisix/dashboard_config.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - dataease-etcd

networks:
  dev:
    external: true
    name: dev
    driver: bridge
