x-default-services: &default-services
  networks:
    - dev
  environment:
    TZ: Asia/Shanghai

services:
  postgres:
    image: postgres:16
    container_name: postgres
    <<: *default-services
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      # PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${PASSWORD}

  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    <<: *default-services
    ports:
      - "5433:5432"
    volumes:
      - ./pgvector:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}

  mysql57:
    image: mysql:5.7
    container_name: mysql57
    <<: *default-services
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql57/data:/var/lib/mysql
      - ./mysql57/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}

  mysql:
    image: mysql:8.3
    container_name: mysql
    <<: *default-services
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}

  redis:
    image: redis
    container_name: redis
    <<: *default-services
    command: [ "redis-server", "--bind", "0.0.0.0", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # https://github.com/bitnami/containers/tree/main/bitnami/kafka#how-to-use-this-image
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    <<: *default-services
    ports:
      - "9092:9092"
    volumes:
      - ./kafka:/bitnami/kafka
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

  # https://github.com/provectus/kafka-ui
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    <<: *default-services
    ports:
      - "9093:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  nginx:
    image: nginx
    container_name: nginx
    <<: *default-services
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/

  minio:
    image: minio/minio
    container_name: minio
    <<: *default-services
    ports:
      - "9000:9000"   # api port
      - "9090:9090"   # console
    volumes:
      - ./minio/config:/root/.minio
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"

networks:
  dev:
    # docker network create dev -d bridge
    external: true
