FROM debian

MAINTAINER "tuke tukeof@gmail.com"

RUN apt-get update -y && \
    apt-get install -y apt-utils imagemagick graphicsmagick


# wget ftp://ftp.graphicsmagick.org/pub/GraphicsMagick/GraphicsMagick-LATEST.tar.gz
# tar -xzvf GraphicsMagick-LATEST.tar.gz
# yum install -y libpng libjpeg libpng-devel libjpeg-devel ghostscript libtiff libtiff-devel freetype freetype-devel jasper jasper-devel
# cd `ls | grep GraphicsMagick | grep -v tar.gz`
# ./configure
# make
# make install
